### ISSUE TITLE
Incompatibility with Legacy4J.

### ISSUE THREAD

**Issue by DiamondYoshi** [kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric#37]
Startup fails when the 2 are used together.
![Screenshot from 2024-07-31 00-45-58](https://github.com/user-attachments/assets/95c8a39a-b97c-4060-914c-745e2763a228)

**Comment by mdcfe** [comment]
Legacy4J [explicitly blocks this mod](https://github.com/Wilyicaro/Legacy-Minecraft/blob/1.20.4/fabric/src/main/resources/fabric.mod.json#L39). This is probably because Legacy4J appears to replace several parts of the main menu and loading screens, which would break this mod.

If you want the functionality of this mod, I'd suggest reaching out to Legacy4J and asking them if there's a way to make it compatible - Wilyicaro/Legacy-Minecraft#69 suggests it may not be.
